# Generated by Django 3.2.4 on 2021-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.CharField(max_length=5)),
                ('light', models.CharField(max_length=3)),
            ],
        ),
    ]
